name: Terraform Staging

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        
  deploy:
      runs-on: ubuntu-latest

      env:
        COOP_ADMIN_EMAIL: ${{ secrets.COOP_ADMIN_EMAIL }}
        COOP_ADMIN_PASSWORD: ${{ secrets.COOP_ADMIN_PASSWORD }}
        GRAPHQL_OPAQUE_SCALAR_SECRET: ${{ secrets.GRAPHQL_OPAQUE_SCALAR_SECRET }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

      steps:
        - uses: actions/checkout@v4

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: eu-central-2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Retrieve Terraform Outputs
          run: |
            cd terraform
            terraform init
            SERVER_IP=$(terraform output -raw instance_public_ip)
            echo "SERVER_IP=$SERVER_IP" >> "$GITHUB_ENV"
            terraform output -raw private_key > ../private_key.pem
            chmod 600 ../private_key.pem

        - name: Populate env secrets into coop.env
          run: |
            sed -i "s|COOP_ADMIN_EMAIL=.*|COOP_ADMIN_EMAIL=$COOP_ADMIN_EMAIL|g" coop/coop.env
            sed -i "s|COOP_ADMIN_PASSWORD=.*|COOP_ADMIN_PASSWORD=$COOP_ADMIN_PASSWORD|g" coop/coop.env
            sed -i "s|GRAPHQL_OPAQUE_SCALAR_SECRET=.*|GRAPHQL_OPAQUE_SCALAR_SECRET=$GRAPHQL_OPAQUE_SCALAR_SECRET|g" coop/coop.env
            sed -i "s|SESSION_SECRET=.*|SESSION_SECRET=$SESSION_SECRET|g" coop/coop.env

        - name: Copy files and deploy to EC2
          run: |
            tar -czf coop.tar.gz coop/
            scp -o StrictHostKeyChecking=no -i private_key.pem coop.tar.gz ubuntu@$SERVER_IP:/home/ubuntu/
            ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$SERVER_IP "
              tar -xzf coop.tar.gz
              chmod +x coop/install-docker.sh
              ./coop/install-docker.sh
              cd coop
              sudo docker compose up -d --build
            "